// Generated by CoffeeScript 2.3.1
var Display;

import React from "react";

import {
  View,
  Text,
  Platform
} from "react-native";

import ErrorBoundary from "./components/ErrorBoundary";

import socket, {
  join_game
} from "./socket";

// determines how to display
export default Display = class Display extends React.Component({
    // constructor(){
    //   this.state = {stage: /* from channel */}
    // }
    render: function() {
      console.log(join_game(socket, "test game", "p1"));
      return <ErrorBoundary>
      {<Text>{      // Platform.OS === "web" ? <Page/> : <Screen/>
(Platform.OS === "web" ? "web" : "screen")}</Text>}
    </ErrorBoundary>;
    }
  }) {};
